services:
  - type: worker
    name: deriv-bot
    env: python
    repo: https://github.com/kheeng-11/bot
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
